server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 100m;

  location /api/ {
    proxy_pass http://api:8000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # streaming SSE do chat
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 900s;
  }

  location / {
    try_files $uri /index.html;
  }
}
